In [1]:
import pandas as pd
import numpy as np

In [70]:
tmp1 = pd.read_csv("data/01aJourneyDataExtract10Jan16-23Jan16.csv")
tmp1['EndStation Id'] = tmp1['EndStation Id'].fillna(9999).astype('int64')
tmp1['EndStation Name'] = tmp1['EndStation Name'].fillna('unknown')
tmp1['EndStation Name'] = tmp1['EndStation Name'].replace(" ,", ",")
tmp1['StartStation Id'] = tmp1['EndStation Id'].fillna(9999).astype('int64')
tmp1['StartStation Name'] = tmp1['StartStation Name'].fillna('unknown')
tmp1['StartStation Name'] = tmp1['StartStation Name'].replace(" ,", ",")
tmp1['Bike Id'] = tmp1['Bike Id'].fillna(0)
tmp1['End Date'] = pd.to_datetime(tmp1['End Date'])
tmp1['Start Date'] = pd.to_datetime(tmp1['Start Date'])
tmp1['Bike Model'] = 'CLASSIC'
tmp1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284587 entries, 0 to 284586
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Rental Id          284587 non-null  int64
 1   Duration           284587 non-null  int64
 2   Bike Id            284587 non-null  int64
 3   End Date           284587 non-null  datetime64[ns]
 4   EndStation Id      284587 non-null  int64
 5   EndStation Name    284587 non-null  object
 6   Start Date         284587 non-null  datetime64[ns]
 7   StartStation Id    284587 non-null  int64
 8   StartStation Name  284587 non-null  object
 9   Bike Model         284587 non-null  object
dtypes: datetime64[ns](2), int64(5), object(3)
memory usage: 21.7+ MB

In [69]:
tmp1

,Rental Id,Duration,Bike Id,End Date,EndStation Id,EndStation Name,Start Date,StartStation Id,StartStation Name,Bike Model
0,50754225,240,11834,2016-10-01 00:04:00,383,"Frith Street, Soho",2016-10-01 00:00:00,383,"Drury Lane, Covent Garden",CLASSIC
1,50754226,300,9648,2016-10-01 00:05:00,719,"Victoria Park Road, Hackney Central",2016-10-01 00:00:00,719,"Pott Street, Bethnal Green",CLASSIC
2,50754227,1200,10689,2016-10-01 00:20:00,272,"Baylis Road, Waterloo",2016-10-01 00:00:00,272,"Harrington Square 2, Camden Town",CLASSIC
3,50754228,780,8593,2016-10-01 00:14:00,471,"Hewison Street, Old Ford",2016-10-01 00:01:00,471,"Canton Street, Poplar",CLASSIC
4,50754229,600,8619,2016-10-01 00:11:00,399,"Brick Lane Market, Shoreditch",2016-10-01 00:01:00,399,"Cephas Street, Bethnal Green",CLASSIC
...,...,...,...,...,...,...,...,...,...,...
284582,51071167,480,5304,2016-01-23 17:10:00,200,"LMU Commercial Road, Whitechapel",2016-01-23 17:02:00,200,"Jewry Street, Aldgate",CLASSIC
284583,51071169,60,13298,2016-01-23 19:14:00,104,"Crosswall, Tower",2016-01-23 19:13:00,104,"Jewry Street, Aldgate",CLASSIC
284584,51071170,60,7388,2016-01-23 21:01:00,104,"Crosswall, Tower",2016-01-23 21:00:00,104,"Jewry Street, Aldgate",CLASSIC
284585,51109280,840,13350,2016-01-22 14:47:00,471,"Hewison Street, Old Ford",2016-01-22 14:33:00,471,"Canton Street, Poplar",CLASSIC
284586,51109295,900,7705,2016-01-23 14:50:00,471,"Hewison Street, Old Ford",2016-01-23 14:35:00,471,"Canton Street, Poplar",CLASSIC

In [65]:
tmp1.to_parquet('01aJourneyDataExtract10Jan16-23Jan16.parquet', compression='gzip')

In [113]:
tmp2 = pd.read_csv("data/336JourneyDataExtract19Sep2022-25Sep2022.csv")
tmp2.drop(columns='Total duration', inplace=True)
tmp2.rename(columns={
    'Number': 'Rental Id',
    'Start date':'Start Date',
    'Start station number': 'StartStation Id',
    'Start station': 'StartStation Name',
    'End date': 'End Date',
    'End station number':'EndStation Id',
    'End station': 'EndStation Name',
    'Bike number': 'Bike Id',
    'Bike model': 'Bike Model',
    'Total duration (ms)': 'Duration'
}, inplace=True)
tmp2['Duration'] = (tmp2['Duration']/60).astype('int64')
tmp2['StartStation Id'] = tmp2['StartStation Id'].replace('300006-1', '300006').fillna(999999).astype('int64')
tmp2['EndStation Id'] = tmp2['EndStation Id'].replace('300006-1', '300006').fillna(999999).astype('int64')
tmp2['EndStation Name'] = tmp2['EndStation Name'].fillna('unknown')
tmp2['EndStation Name'] = tmp2['EndStation Name'].replace(" ,", ",")
tmp2['StartStation Name'] = tmp2['StartStation Name'].fillna('unknown')
tmp2['StartStation Name'] = tmp2['StartStation Name'].replace(" ,", ",")
tmp2['Bike Id'] = tmp2['Bike Id'].fillna(0)
tmp2['End Date'] = pd.to_datetime(tmp2['End Date'])
tmp2['Start Date'] = pd.to_datetime(tmp2['Start Date'])

In [114]:
tmp2[tmp2['StartStation Name'].str.contains('Coomer')]

,Rental Id,Start Date,StartStation Id,StartStation Name,End Date,EndStation Id,EndStation Name,Bike Id,Bike Model,Duration
449,125423586,2022-09-25 22:26:00,300006,"Coomer Place, West Kensington_OLD",2022-09-25 22:34:00,3459,"Collingham Gardens, Earl's Court",55191,CLASSIC,7714
1677,125422330,2022-09-25 20:12:00,300006,"Coomer Place, West Kensington_OLD",2022-09-25 20:22:00,1172,"Queen's Gate (South), South Kensington",52797,CLASSIC,10059
2913,125421046,2022-09-25 18:58:00,300006,"Coomer Place, West Kensington_OLD",2022-09-25 19:24:00,300006,"Coomer Place, West Kensington_OLD",52332,CLASSIC,26326
3315,125420630,2022-09-25 18:38:00,300006,"Coomer Place, West Kensington_OLD",2022-09-25 19:04:00,1182,"Notting Hill Gate Station, Notting Hill",57747,CLASSIC,26525
3316,125420631,2022-09-25 18:38:00,300006,"Coomer Place, West Kensington_OLD",2022-09-25 19:04:00,1182,"Notting Hill Gate Station, Notting Hill",51893,CLASSIC,26526
...,...,...,...,...,...,...,...,...,...,...
175850,125241110,2022-09-19 14:07:00,300006,"Coomer Place, West Kensington_OLD",2022-09-19 14:20:00,1172,"Queen's Gate (South), South Kensington",58291,CLASSIC,12472
179629,125237180,2022-09-19 12:02:00,300006,"Coomer Place, West Kensington_OLD",2022-09-19 12:13:00,200059,"Crisp Road, Hammersmith",50711,CLASSIC,10941
181369,125235421,2022-09-19 10:37:00,300006,"Coomer Place, West Kensington_OLD",2022-09-19 11:03:00,1174,"Alderney Street, Pimlico",24149,CLASSIC,25979
181477,125235311,2022-09-19 10:31:00,300006,"Coomer Place, West Kensington_OLD",2022-09-19 10:46:00,1002,"Holy Trinity Brompton, Knightsbridge",15791,CLASSIC,14495
182709,125234008,2022-09-19 09:32:00,300006,"Coomer Place, West Kensington_OLD",2022-09-19 09:39:00,200069,"Knaresborough Place, Earl's Court",20159,CLASSIC,6804

In [115]:
pd.concat([tmp1,tmp2])

,Rental Id,Duration,Bike Id,End Date,EndStation Id,EndStation Name,Start Date,StartStation Id,StartStation Name,Bike Model
0,50754225,240,11834,2016-10-01 00:04:00,383,"Frith Street, Soho",2016-10-01 00:00:00,383,"Drury Lane, Covent Garden",CLASSIC
1,50754226,300,9648,2016-10-01 00:05:00,719,"Victoria Park Road, Hackney Central",2016-10-01 00:00:00,719,"Pott Street, Bethnal Green",CLASSIC
2,50754227,1200,10689,2016-10-01 00:20:00,272,"Baylis Road, Waterloo",2016-10-01 00:00:00,272,"Harrington Square 2, Camden Town",CLASSIC
3,50754228,780,8593,2016-10-01 00:14:00,471,"Hewison Street, Old Ford",2016-10-01 00:01:00,471,"Canton Street, Poplar",CLASSIC
4,50754229,600,8619,2016-10-01 00:11:00,399,"Brick Lane Market, Shoreditch",2016-10-01 00:01:00,399,"Cephas Street, Bethnal Green",CLASSIC
...,...,...,...,...,...,...,...,...,...,...
186429,125230184,13844,57421,2022-09-19 00:14:00,200014,"Gunmakers Lane, Old Ford",2022-09-19 00:00:00,3427,"Fanshaw Street, Hoxton",CLASSIC
186430,125230185,9535,17815,2022-09-19 00:10:00,1194,"Westminster University, Marylebone",2022-09-19 00:00:00,1007,"Drury Lane, Covent Garden",CLASSIC
186431,125230186,7234,51520,2022-09-19 00:08:00,988,"Great Russell Street, Bloomsbury",2022-09-19 00:00:00,1097,"Northumberland Avenue, Strand",CLASSIC
186432,125230187,21993,51557,2022-09-19 00:22:00,300081,"Haggerston Road, Haggerston",2022-09-19 00:00:00,22183,"Crinan Street, King's Cross",CLASSIC
186433,125230188,30350,51804,2022-09-19 00:31:00,1193,"Kensington Gore, Knightsbridge",2022-09-19 00:00:00,300082,"Bridge Avenue, Hammersmith",CLASSIC

In [117]:
import os
for file in os.listdir('data'):
    print(os.path.join('data',file))

data/134JourneyDataExtract31Oct2018-06Nov2018.csv
data/133JourneyDataExtract24Oct2018-30Oct2018.csv
data/363JourneyDataExtract27Mar2023-02Apr2023.csv
data/318JourneyDataExtract18May2022-24May2022.csv
data/141JourneyDataExtract19Dec2018-25Dec2018.csv
data/332JourneyDataExtract24Aug2022-30Aug2022.csv
data/283JourneyDataExtract15Sep2021-21Sep2021.csv
data/39JourneyDataExtract04Jan2017-10Jan2017.csv
data/2a.JourneyDataExtract01Feb15-14Feb15.csv
data/59JourneyDataExtract24May2017-30May2017.csv
data/248JourneyDataExtract13Jan2021-19Jan2021.csv
data/28JourneyDataExtract19Oct2016-25Oct2016.csv
data/216JourneyDataExtract27May2020-02Jun2020.csv
data/94JourneyDataExtract24Jan2018-30Jan2018.csv
data/102JourneyDataExtract21Mar2018-27Mar2018.csv
data/67JourneyDataExtract19Jul2017-25Jul2017.csv
data/351JourneyDataExtract02Jan2023-08Jan2023.csv
data/189JourneyDataExtract20Nov2019-26Nov2019.csv
data/242JourneyDataExtract25Nov2020-01Dec2020.csv
data/243JourneyDataExtract02Dec2020-08Dec2020.csv
data/90JourneyDataExtract27Dec2017-02Jan2018.csv
data/257JourneyDataExtract17Mar2021-23Mar2021.csv
data/208JourneyDataExtract01Apr2020-07Apr2020.csv
data/314JourneyDataExtract20Apr2022-26Apr2022.csv
data/262JourneyDataExtract21Apr2021-27Apr2021.csv
data/206JourneyDataExtract18Mar2020-24Mar2020.csv
data/294JourneyDataExtract01Dec2021-07Dec2021.csv
data/4a.JourneyDataExtract01Apr15-16Apr15.csv
data/124JourneyDataExtract22Aug2018-28Aug2018.csv
data/104JourneyDataExtract04Apr2018-10Apr2018.csv
data/118JourneyDataExtract11July2018-17July2018.csv
data/71JourneyDataExtract15Aug2017-22Aug2017.csv
data/cyclehireusagestats-2014.zip
data/292JourneyDataExtract17Nov2021-23Nov2021.csv
data/9b-Journey-Data-Extract-06Sep15-19Sep15.csv
data/165JourneyDataExtract05Jun2019-11Jun2019.csv
data/295JourneyDataExtract08Dec2021-14Dec2021.csv
data/96JourneyDataExtract07Feb2018-13Feb2018.csv
data/154JourneyDataExtract20Mar2019-26Mar2019.csv
data/220JourneyDataExtract24Jun2020-30Jun2020.csv
data/108JourneyDataExtract02May2018-08May2018.csv
data/12bJourneyDataExtract28Nov15-12Dec15.csv
data/145JourneyDataExtract16Jan2019-22Jan2019.csv
data/148JourneyDataExtract06Feb2019-12Feb2019.csv
data/89JourneyDataExtract20Dec2017-26Dec2017.csv
data/300JourneyDataExtract12Jan2022-18Jan2022.csv
data/11a-Journey-Data-Extract-18Oct15-31Oct15.csv
data/1a.JourneyDataExtract04Jan15-17Jan15.csv
data/181JourneyDataExtract25Sep2019-01Oct2019.csv
data/173JourneyDataExtract31Jul2019-06Aug2019.csv
data/11b-Journey-Data-Extract-01Nov15-14Nov15.csv
data/178JourneyDataExtract04Sep2019-10Sep2019.csv
data/35JourneyDataExtract07Dec2016-13Dec2016.csv
data/40JourneyDataExtract11Jan2017-17Jan2017.csv
data/65JourneyDataExtract05Jul2017-11Jul2017.csv
data/203JourneyDataExtract26Feb2020-03Mar2020.csv
data/109JourneyDataExtract09May2018-15May2018.csv
data/46JourneyDataExtract22Feb2017-28Feb2017.csv
data/87JourneyDataExtract06Dec2017-12Dec2017.csv
data/331JourneyDataExtract17Aug2022-23Aug2022.csv
data/72JourneyDataExtract23Aug2017-29Aug2017.csv
data/01aJourneyDataExtract10Jan16-23Jan16.csv
data/127JourneyDataExtract12Sep2018-18Sep2018.csv
data/62JourneyDataExtract14Jun2017-20Jun2017.csv
data/cyclehireusagestats-2012.zip
data/22JourneyDataExtract07Sep2016-13Sep2016.csv
data/352JourneyDataExtract09Jan2023-15Jan2023.csv
data/95JourneyDataExtract31Jan2018-06Feb2018.csv
data/266JourneyDataExtract19May2021-25May2021.csv
data/185JourneyDataExtract23Oct2019-29Oct2019.csv
data/113JourneyDataExtract06June2018-12June2018.csv
data/187JourneyDataExtract06Nov2019-12Nov2019.csv
data/170JourneyDataExtract10Jul2019-16Jul2019.csv
data/155JourneyDataExtract27Mar2019-02Apr2019.csv
data/03JourneyDataExtract06Mar2016-31Mar2016.csv
data/184JourneyDataExtract16Oct2019-22Oct2019.csv
data/334JourneyDataExtract07Sep2022-11Sep2022.csv
data/285JourneyDataExtract29Sep2021-05Oct2021.csv
data/360JourneyDataExtract06Mar2023-12Mar2023.csv
data/254JourneyDataExtract24Feb2021-02Mar2021.csv
data/232JourneyDataExtract16Sep2020-22Sep2020.csv
data/356JourneyDataExtract06Feb2023-12Feb2023.csv
data/54JourneyDataExtract19Apr2017-25Apr2017.csv
data/361JourneyDataExtract13Mar2023-19Mar2023.csv
data/04JourneyDataExtract01Apr2016-30Apr2016.csv
data/163JourneyDataExtract22May2019-28May2019.csv
data/78JourneyDataExtract04Oct2017-10Oct2017.csv
data/150JourneyDataExtract20Feb2019-26Feb2019.csv
data/214JourneyDataExtract13May2020-19May2020.csv
data/137JourneyDataExtract21Nov2018-27Nov2018.csv
data/355JourneyDataExtract30Jan2023-05Feb2023.csv
data/228JourneyDataExtract19Aug2020-25Aug2020.csv
data/192JourneyDataExtract11Dec2019-17Dec2019.csv
data/2015TripDatazip.zip
data/172JourneyDataExtract24Jul2019-30Jul2019.csv
data/86JourneyDataExtract29Nov2017-05Dec2017.csv
data/348JourneyDataExtract12Dec2022-18Dec2022.csv
data/131JourneyDataExtract10Oct2018-16Oct2018.csv
data/101JourneyDataExtract14Mar2018-20Mar2018.csv
data/205JourneyDataExtract11Mar2020-17Mar2020.csv
data/342JourneyDataExtract31Oct2022-06Nov2022.csv
data/273JourneyDataExtract07Jul2021-13Jul2021.csv
data/106JourneyDataExtract18Apr2018-24Apr2018.csv
data/322JourneyDataExtract15Jun2022-21Jun2022.csv
data/246JourneyDataExtract23Dec2020-29Dec2020.csv
data/117JourneyDataExtract04July2018-10July2018.csv
data/326JourneyDataExtract13Jul2022-19Jul2022.csv
data/245JourneyDataExtract16Dec2020-22Dec2020.csv
data/105JourneyDataExtract11Apr2018-17Apr2018.csv
data/142JourneyDataExtract26Dec2018-01Jan2019.csv
data/44JourneyDataExtract08Feb2017-14Feb2017.csv
data/115JourneyDataExtract20June2018-26June2018.csv
data/298JourneyDataExtract29Dec2021-04Jan2022.csv
data/42JourneyDataExtract25Jan2017-31Jan2017.csv
data/304JourneyDataExtract09Feb2022-15Feb2022.csv
data/270JourneyDataExtract16Jun2021-22Jun2021.csv
data/296JourneyDataExtract15Dec2021-21Dec2021.csv
data/281JourneyDataExtract01Sep2021-07Sep2021.csv
data/151JourneyDataExtract27Feb2019-05Mar2019.csv
data/143JourneyDataExtract02Jan2019-08Jan2019.csv
data/132JourneyDataExtract17Oct2018-23Oct2018.csv
data/221JourneyDataExtract01Jul2020-07Jul2020.csv
data/238JourneyDataExtract28Oct2020-03Nov2020.csv
data/38JourneyDataExtract28Dec2016-03Jan2017.csv
data/313JourneyDataExtract13Apr2022-19Apr2022.csv
data/323JourneyDataExtract22Jun2022-28Jun2022.csv
data/213JourneyDataExtract06May2020-12May2020.csv
data/30JourneyDataExtract02Nov2016-08Nov2016.csv
data/347JourneyDataExtract05Dec2022-11Dec2022.csv
data/179JourneyDataExtract11Sep2019-17Sep2019.csv
data/302JourneyDataExtract26Jan2022-01Feb2022.csv
data/207JourneyDataExtract25Mar2020-31Mar2020.csv
data/219JourneyDataExtract17Jun2020-23Jun2020.csv
data/268JourneyDataExtract02Jun2021-08Jun2021.csv
data/129JourneyDataExtract26Sep2018-02Oct2018.csv
data/197JourneyDataExtract15Jan2020-21Jan2020.csv
data/274JourneyDataExtract14Jul2021-20Jul2021.csv
data/167JourneyDataExtract19Jun2019-25Jun2019.csv
data/201JourneyDataExtract12Feb2020-18Feb2020.csv
data/103JourneyDataExtract28Mar2018-03Apr2018.csv
data/319JourneyDataExtract25May2022-31May2022.csv
data/53JourneyDataExtract12Apr2017-18Apr2017.csv
data/346JourneyDataExtract28Nov2022-04Dec2022.csv
data/8b-Journey-Data-Extract-08Aug15-22Aug15.csv
data/308JourneyDataExtract09Mar2022-15Mar2022.csv
data/47JourneyDataExtract01Mar2017-07Mar2017.csv
data/158JourneyDataExtract17Apr2019-23Apr2019.csv
data/249JourneyDataExtract20Jan2021-26Jan2021.csv
data/93JourneyDataExtract17Jan2018-23Jan2018.csv
data/359JourneyDataExtract27Feb2023-05Mar2023.csv
data/271JourneyDataExtract23Jun2021-29Jun2021.csv
data/147JourneyDataExtract30Jan2019-05Feb2019.csv
data/180JourneyDataExtract18Sep2019-24Sep2019.csv
data/297JourneyDataExtract22Dec2021-28Dec2021.csv
data/191JourneyDataExtract04Dec2019-10Dec2019.csv
data/cyclehireusagestats-2013.zip
data/275JourneyDataExtract21Jul2021-27Jul2021.csv
data/169JourneyDataExtract03Jul2019-09Jul2019.csv
data/97JourneyDataExtract14Feb2018-20Feb2018.csv
data/114JourneyDataExtract13June2018-19June2018.csv
data/4b.JourneyDataExtract 17Apr15-02May15.csv
data/343JourneyDataExtract07Nov2022-13Nov2022.csv
data/14JourneyDataExtract13Jul2016-19Jul2016.csv
data/175JourneyDataExtract14Aug2019-20Aug2019.csv
data/2b.JourneyDataExtract15Feb15-28Feb15.csv
data/310JourneyDataExtract23Mar2022-29Mar2022.csv
data/159JourneyDataExtract24Apr2019-30Apr2019.csv
data/289JourneyDataExtract27Oct2021-02Nov2021.csv
data/288JourneyDataExtract20Oct2021-26Oct2021.csv
data/303JourneyDataExtract02Feb2022-08Feb2022.csv
data/218JourneyDataExtract10Jun2020-16Jun2020.csv
data/29JourneyDataExtract26Oct2016-01Nov2016.csv
data/177JourneyDataExtract28Aug2019-03Sep2019.csv
data/183JourneyDataExtract09Oct2019-15Oct2019.csv
data/329JourneyDataExtract03Aug2022-09Aug2022.csv
data/01bJourneyDataExtract24Jan16-06Feb16.csv
data/215JourneyDataExtract20May2020-26May2020.csv
data/194JourneyDataExtract25Dec2019-31Dec2019.csv
data/222JourneyDataExtract08Jul2020-14Jul2020.csv
data/333JourneyDataExtract31Aug2022-06Sep2022.csv
data/168JourneyDataExtract26Jun2019-02Jul2019.csv
data/144JourneyDataExtract09Jan2019-15Jan2019.csv
data/43JourneyDataExtract01Feb2017-07Feb2017.csv
data/48JourneyDataExtract08Mar2017-14Mar2017.csv
data/309JourneyDataExtract16Mar2022-22Mar2022.csv
data/277JourneyDataExtract04Aug2021-10Aug2021.csv
data/92JourneyDataExtract10Jan2018-16Jan2018.csv
data/76JourneyDataExtract20Sep2017-26Sep2017.csv
data/23JourneyDataExtract14Sep2016-20Sep2016.csv
data/282JourneyDataExtract08Sep2021-14Sep2021.csv
data/176JourneyDataExtract21Aug2019-27Aug2019.csv
data/327JourneyDataExtract20Jul2022-26Jul2022.csv
data/195JourneyDataExtract01Jan2020-07Jan2020.csv
data/08JourneyDataExtract01Jun2016-07Jun2016.csv
data/116JourneyDataExtract27June2018-03July2018.csv
data/51 Journey Data Extract 29Mar2017-04Apr2017.csv
data/354JourneyDataExtract23Jan2023-29Jan2023.csv
data/335JourneyDataExtract12Sep2022-18Sep2022.csv
data/209JourneyDataExtract08Apr2020-14Apr2020.csv
data/263JourneyDataExtract28Apr2021-04May2021.csv
data/8a-Journey-Data-Extract-26Jul15-07Aug15.csv
data/6aJourneyDataExtract31May15-12Jun15.csv
data/18JourneyDataExtract10Aug2016-16Aug2016.csv
data/345JourneyDataExtract21Nov2022-27Nov2022.csv
data/149JourneyDataExtract13Feb2019-19Feb2019.csv
data/276JourneyDataExtract28Jul2021-03Aug2021.csv
data/357JourneyDataExtract13Feb2023-19Feb2023.csv
data/58JourneyDataExtract17May2017-23May2017.csv
data/200JourneyDataExtract05Feb2020-11Feb2020.csv
data/85JourneyDataExtract22Nov2017-28Nov2017.csv
data/125JourneyDataExtract29Aug2018-04Sep2018.csv
data/81JourneyDataExtract25Oct2017-31Oct2017.csv
data/41JourneyDataExtract18Jan2017-24Jan2017.csv
data/111JourneyDataExtract23May2018-29May2018.csv
data/350JourneyDataExtract26Dec2022-01Jan2023.csv
data/7b.JourneyDataExtract12Jul15-25Jul15.csv
data/01b Journey Data Extract 24Jan16-06Feb16.csv
data/107JourneyDataExtract25Apr2018-01May2018.csv
data/26JourneyDataExtract05Oct2016-11Oct2016.csv
data/10b-Journey-Data-Extract-04Oct15-17Oct15.csv
data/123JourneyDataExtract15Aug2018-21Aug2018.csv
data/112JourneyDataExtract30May2018-05June2018.csv
data/11JourneyDataExtract22Jun2016-28Jun2016.csv
data/338JourneyDataExtract03Oct2022-09Oct2022.csv
data/75JourneyDataExtract13Sep2017-19Sep2017.csv
data/166JourneyDataExtract12Jun2019-18Jun2019.csv
data/256JourneyDataExtract10Mar2021-16Mar2021.csv
data/237JourneyDataExtract21Oct2020-27Oct2020.csv
data/174JourneyDataExtract07Aug2019-13Aug2019.csv
data/156JourneyDataExtract03Apr2019-09Apr2019.csv
data/74JourneyDataExtract06Sep2017-12Sep2017.csv
data/306JourneyDataExtract23Feb2022-01Mar2022.csv
data/19JourneyDataExtract17Aug2016-23Aug2016.csv
data/126JourneyDataExtract05Sep2018-11Sep2018.csv
data/272JourneyDataExtract30Jun2021-06Jul2021.csv
data/265JourneyDataExtract12May2021-18May2021.csv
data/1b.JourneyDataExtract18Jan15-31Jan15.csv
data/339JourneyDataExtract10Oct2022-16Oct2022.csv
data/77JourneyDataExtract27Sep2017-03Oct2017.csv
data/110JourneyDataExtract16May2018-22May2018.csv
data/353JourneyDataExtract16Jan2023-22Jan2023.csv
data/3b.JourneyDataExtract16Mar15-31Mar15.csv
data/36JourneyDataExtract14Dec2016-20Dec2016.csv
data/31JourneyDataExtract09Nov2016-15Nov2016.csv
data/98JourneyDataExtract21Feb2018-27Feb2018.csv
data/128JourneyDataExtract19Sep2018-25Sep2018.csv
data/50 Journey Data Extract 22Mar2017-28Mar2017.csv
data/84JourneyDataExtract15Nov2017-21Nov2017.csv
data/186JourneyDataExtract30Oct2019-05Nov2019.csv
data/09JourneyDataExtract08Jun2016-14Jun2016.csv
data/236JourneyDataExtract14Oct2020-20Oct2020.csv
data/15JourneyDataExtract20Jul2016-26Jul2016.csv
data/330JourneyDataExtract10Aug2022-16Aug2022.csv
data/320JourneyDataExtract01Jun2022-07Jun2022.csv
data/9a-Journey-Data-Extract-23Aug15-05Sep15.csv
data/164JourneyDataExtract29May2019-04Jun2019.csv
data/64JourneyDataExtract28Jun2017-04Jul2017.csv
data/146JourneyDataExtract23Jan2019-29Jan2019.csv
data/239JourneyDataExtract04Nov2020-10Nov2020.csv
data/66JourneyDataExtract12Jul2017-18Jul2017.csv
data/13aJourneyDataExtract13Dec15-24Dec15.csv
data/305JourneyDataExtract16Feb2022-22Feb2022.csv
data/7a.JourneyDataExtract28Jun15-11Jul15.csv
data/56JourneyDataExtract 03May2017-09May2017.csv
data/202JourneyDataExtract19Feb2020-25Feb2020.csv
data/223JourneyDataExtract15Jul2020-21Jul2020.csv
data/16JourneyDataExtract27Jul2016-02Aug2016.csv
data/280JourneyDataExtract25Aug2021-31Aug2021.csv
data/130JourneyDataExtract03Oct2018-09Oct2018.csv
data/258JourneyDataExtract24Mar2021-30Mar2021.csv
data/241JourneyDataExtract18Nov2020-24Nov2020.csv
data/119JourneyDataExtract18July2018-24July2018.csv
data/233JourneyDataExtract23Sep2020-29Sep2020.csv
data/227JourneyDataExtract12Aug2020-18Aug2020.csv
data/261JourneyDataExtract14Apr2021-20Apr2021.csv
data/293JourneyDataExtract24Nov2021-30Nov2021.csv
data/171JourneyDataExtract17Jul2019-23Jul2019.csv
data/45JourneyDataExtract15Feb2017-21Feb2017.csv
data/34JourneyDataExtract30Nov2016-06Dec2016.csv
data/269JourneyDataExtract09Jun2021-15Jun2021.csv
data/244JourneyDataExtract09Dec2020-15Dec2020.csv
data/349JourneyDataExtract19Dec2022-25Dec2022.csv
data/07JourneyDataExtract25May2016-31May2016.csv
data/61JourneyDataExtract07Jun2017-13Jun2017.csv
data/196JourneyDataExtract08Jan2020-14Jan2020.csv
data/362JourneyDataExtract20Mar2023-26Mar2023.csv
data/02bJourneyDataExtract21Feb16-05Mar2016.csv
data/286JourneyDataExtract06Oct2021-12Oct2021.csv
data/253JourneyDataExtract17Feb2021-23Feb2021.csv
data/3a.JourneyDataExtract01Mar15-15Mar15.csv
data/63JourneyDataExtract21Jun2017-27Jun2017.csv
data/121JourneyDataExtract01Aug2018-07Aug2018.csv
data/153JourneyDataExtract13Mar2019-19Mar2019.csv
data/139JourneyDataExtract05Dec2018-11Dec2018.csv
data/49JourneyDataExtract15Mar2017-21Mar2017.xlsx
data/138JourneyDataExtract28Nov2018-04Dec2018.csv
data/230JourneyDataExtract02Sep2020-08Sep2020.csv
data/70JourneyDataExtract08Aug2017-14Aug2017.csv
data/316JourneyDataExtract04May2022-10May2022.csv
data/240JourneyDataExtract11Nov2020-17Nov2020.csv
data/198JourneyDataExtract22Jan2020-28Jan2020.csv
data/204JourneyDataExtract04Mar2020-10Mar2020.csv
data/20JourneyDataExtract24Aug2016-30Aug2016.csv
data/120JourneyDataExtract25July2018-31July2018.csv
data/12JourneyDataExtract29Jun2016-05Jul2016.csv
data/136JourneyDataExtract14Nov2018-20Nov2018.csv
data/251JourneyDataExtract03Feb2021-09Feb2021.csv
data/212JourneyDataExtract29Apr2020-05May2020.csv
data/260JourneyDataExtract07Apr2021-13Apr2021.csv
data/79JourneyDataExtract11Oct2017-17Oct2017.csv
data/211JourneyDataExtract22Apr2020-28Apr2020.csv
data/344JourneyDataExtract14Nov2022-20Nov2022.csv
data/32JourneyDataExtract16Nov2016-22Nov2016.csv
data/321JourneyDataExtract08Jun2022-14Jun2022.csv
data/190JourneyDataExtract27Nov2019-03Dec2019.csv
data/224JourneyDataExtract22Jul2020-28Jul2020.csv
data/05JourneyDataExtract01May2016-17May2016.csv
data/80JourneyDataExtract18Oct2017-24Oct2017.csv
data/140JourneyDataExtract12Dec2018-18Dec2018.csv
data/328JourneyDataExtract27Jul2022-02Aug2022.csv
data/278JourneyDataExtract11Aug2021-17Aug2021.csv
data/73JourneyDataExtract30Aug2017-05Sep2017.csv
data/188JourneyDataExtract13Nov2019-19Nov2019.csv
data/122JourneyDataExtract08Aug2018-14Aug2018.csv
data/2016TripDataZip.zip
data/182JourneyDataExtract02Oct2019-08Oct2019.csv
data/13bJourneyDataExtract25Dec15-09Jan16.csv
data/100JourneyDataExtract07Mar2018-13Mar2018.csv
data/24JourneyDataExtract21Sep2016-27Sep2016.csv
data/6bJourneyDataExtract13Jun15-27Jun15.csv
data/82JourneyDataExtract01Nov2017-07Nov2017.csv
data/88JourneyDataExtract13Dec2017-19Dec2017.csv
data/290JourneyDataExtract03Nov2021-09Nov2021.csv
data/69JourneyDataExtract01Aug2017-07Aug2017.csv
data/250JourneyDataExtract27Jan2021-02Feb2021.csv
data/12aJourneyDataExtract15Nov15-27Nov15.csv
data/341JourneyDataExtract24Oct2022-30Oct2022.csv
data/226JourneyDataExtract05Aug2020-11Aug2020.csv
data/02aJourneyDataExtract07Fe16-20Feb2016.csv
data/267JourneyDataExtract26May2021-01Jun2021.csv
data/25JourneyDataExtract28Sep2016-04Oct2016.csv
data/284JourneyDataExtract22Sep2021-28Sep2021.csv
data/325JourneyDataExtract06Jul2022-12Jul2022.csv
data/60JourneyDataExtract31May2017-06Jun2017.csv
data/37JourneyDataExtract21Dec2016-27Dec2016.csv
data/83JourneyDataExtract08Nov2017-14Nov2017.csv
data/340JourneyDataExtract17Oct2022-23Oct2022.csv
data/317JourneyDataExtract11May2022-17May2022.csv
data/246JourneyDataExtract30Dec2020-05Jan2021.csv
data/234JourneyDataExtract30Sep2020-06Oct2020.csv
data/312JourneyDataExtract06Apr2022-12Apr2022.csv
data/247JourneyDataExtract06Jan2021-12Jan2021.csv
data/307JourneyDataExtract02Mar2022-08Mar2022.csv
data/252JourneyDataExtract10Feb2021-16Feb2021.csv
data/199JourneyDataExtract29Jan2020-04Feb2020.csv
data/336JourneyDataExtract19Sep2022-25Sep2022.csv
data/10a-Journey-Data-Extract-20Sep15-03Oct15.csv
data/5b.JourneyDataExtract17May15-30May15.csv
data/324JourneyDataExtract29Jun2022-05Jul2022.csv
data/33JourneyDataExtract23Nov2016-29Nov2016.csv
data/99JourneyDataExtract28Feb2018-06Mar2018.csv
data/235JourneyDataExtract07Oct2020-13Oct2020.csv
data/21JourneyDataExtract31Aug2016-06Sep2016.csv
data/210JourneyDataExtract15Apr2020-21Apr2020.csv
data/13JourneyDataExtract06Jul2016-12Jul2016.csv
data/135JourneyDataExtract07Nov2018-13Nov2018.csv
data/10JourneyDataExtract15Jun2016-21Jun2016.csv
data/311JourneyDataExtract30Mar2022-05Apr2022.csv
data/162JourneyDataExtract15May2019-21May2019.csv
data/5a.JourneyDataExtract03May15-16May15.csv
data/337JourneyDataExtract26Sep2022-02Oct2022.csv
data/358JourneyDataExtract20Feb2023-26Feb2023.csv
data/287JourneyDataExtract13Oct2021-19Oct2021.csv
data/259JourneyDataExtract31Mar2021-06Apr2021.csv
data/27JourneyDataExtract12Oct2016-18Oct2016.csv
data/152JourneyDataExtract06Mar2019-12Mar2019.csv
data/55JourneyData Extract26Apr2017-02May2017.csv
data/91JourneyDataExtract03Jan2018-09Jan2018.csv
data/255JourneyDataExtract03Mar2021-09Mar2021.csv
data/225JourneyDataExtract29Jul2020-04Aug2020.csv
data/291JourneyDataExtract10Nov2021-16Nov2021.csv
data/264JourneyDataExtract05May2021-11May2021.csv
data/68JourneyDataExtract26Jul2017-31Jul2017.csv
data/193JourneyDataExtract18Dec2019-24Dec2019.csv
data/217JourneyDataExtract03Jun2020-09Jun2020.csv
data/315JourneyDataExtract27Apr2022-03May2022.csv
data/52 Journey Data Extract 05Apr2017-11Apr2017.csv
data/161JourneyDataExtract08May2019-14May2019.csv
data/231JourneyDataExtract09Sep2020-15Sep2020.csv
data/160JourneyDataExtract01May2019-07May2019.csv
data/229JourneyDataExtract26Aug2020-01Sep2020.csv
data/301JourneyDataExtract19Jan2022-25Jan2022.csv
data/299JourneyDataExtract05Jan2022-11Jan2022.csv
data/57JourneyDataExtract10May2017-16May2017.csv
data/17JourneyDataExtract03Aug2016-09Aug2016.csv
data/157JourneyDataExtract10Apr2019-16Apr2019.csv
data/279JourneyDataExtract18Aug2021-24Aug2021.csv
data/06JourneyDataExtract18May2016-24May2016.csv

In [147]:
df = pd.read_csv("data/341JourneyDataExtract24Oct2022-30Oct2022.csv")

/tmp/ipykernel_18475/1606330073.py:1: DtypeWarning: Columns (2,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/341JourneyDataExtract24Oct2022-30Oct2022.csv")

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202605 entries, 0 to 202604
Data columns (total 11 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Number                202605 non-null  int64
 1   Start date            202605 non-null  object
 2   Start station number  202605 non-null  object
 3   Start station         202605 non-null  object
 4   End date              202605 non-null  object
 5   End station number    202605 non-null  object
 6   End station           202605 non-null  object
 7   Bike number           202605 non-null  int64
 8   Bike model            202605 non-null  object
 9   Total duration        202605 non-null  object
 10  Total duration (ms)   202605 non-null  int64
dtypes: int64(3), object(8)
memory usage: 17.0+ MB

In [150]:
for i, each in enumerate(df['Start station number'][:]):
    if each == '001085':
        print(each)

001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085
001085

In [151]:
df['Start station number'] = df['Start station number'].replace('300006-1', '300006') \
        .replace('200217old2', '200217').replace('001057_old', '001057') \
            .fillna(999999).astype('int64')

In [152]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202605 entries, 0 to 202604
Data columns (total 11 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Number                202605 non-null  int64
 1   Start date            202605 non-null  object
 2   Start station number  202605 non-null  int64
 3   Start station         202605 non-null  object
 4   End date              202605 non-null  object
 5   End station number    202605 non-null  object
 6   End station           202605 non-null  object
 7   Bike number           202605 non-null  int64
 8   Bike model            202605 non-null  object
 9   Total duration        202605 non-null  object
 10  Total duration (ms)   202605 non-null  int64
dtypes: int64(4), object(7)
memory usage: 17.0+ MB

In [153]:
df.to_csv('test.csv', compression='gzip')

In [154]:
df.rename(columns={
        'Number': 'rental_id',
        'Start date':'start_date',
        'Start station number': 'startstation_id',
        'Start station': 'startstation_name',
        'End date': 'end_date',
        'End station number':'endstation_id',
        'End station': 'endstation_name',
        'Bike number': 'bike_id',
        'Bike model': 'bike_model',
        'Total duration (ms)': 'duration'
    }, inplace=True)

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202605 entries, 0 to 202604
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   rental_id          202605 non-null  int64
 1   start_date         202605 non-null  object
 2   startstation_id    202605 non-null  int64
 3   startstation_name  202605 non-null  object
 4   end_date           202605 non-null  object
 5   endstation_id      202605 non-null  object
 6   endstation_name    202605 non-null  object
 7   bike_id            202605 non-null  int64
 8   bike_model         202605 non-null  object
 9   Total duration     202605 non-null  object
 10  duration           202605 non-null  int64
dtypes: int64(4), object(7)
memory usage: 17.0+ MB

In [160]:
def newstyle_cleaning(file_path):
    df = pd.read_csv(f'data/{file_path}')
    df.drop(columns='Total duration', inplace=True)
    df['Total duration (ms)'] = round(df['Total duration (ms)']/60)
    df['Start station number'] = df['Start station number'].replace('300006-1', '300006') \
        .replace('200217old2', '200217').replace('001057_old', '001057') \
            .fillna(999999).astype('int64')
    df['End station number'] = df['End station number'].replace('300006-1', '300006') \
        .replace('200217old2', '200217').replace('001057_old', '001057') \
            .fillna(999999).astype('int64')
    df['End station'] = df['End station'].fillna('unknown')
    df['End station'] = df['End station'].replace(" ,", ",")
    df['Start station'] = df['Start station'].fillna('unknown')
    df['Start station'] = df['Start station'].replace(" ,", ",")
    df['Bike number'] = df['Bike number'].fillna(0)
    df['End date'] = pd.to_datetime(df['End date'])
    df['Start date'] = pd.to_datetime(df['Start date'])
    df.rename(columns={
        'Number': 'rental_id',
        'Start date':'start_date',
        'Start station number': 'startstation_id',
        'Start station': 'startstation_name',
        'End date': 'end_date',
        'End station number':'endstation_id',
        'End station': 'endstation_name',
        'Bike number': 'bike_id',
        'Bike model': 'bike_model',
        'Total duration (ms)': 'duration'
    }, inplace=True)
    return df
df2 =newstyle_cleaning('341JourneyDataExtract24Oct2022-30Oct2022.csv')

/tmp/ipykernel_18475/663760684.py:2: DtypeWarning: Columns (2,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'data/{file_path}')

In [162]:
df2.to_parquet('df2.parquet')